### ISSUE TITLE
Code Review - Group 26

### ISSUE THREAD

**Issue by coltraneyan** [mivgubel/Solidity-Bootcamp-Week-2-Project#6]
> `  const wallet =
    process.env.MNEMONIC && process.env.MNEMONIC.length > 0
      ? ethers.Wallet.fromMnemonic(process.env.MNEMONIC)
      : new ethers.Wallet(process.env.PRIVATE_KEY ?? EXPOSED_KEY);
`
- can you slim this down to be appropriate for a current env in which (I'm assuming) you aren't using MNEMONIC's?

> `  const TokenContract: MyToken = new Contract(
    "0x45fa02999Fb4f5E7C6e64cC1064D61A9fcBF5F14",
    TokenJson.abi,
    signer
  ) as MyToken;`

- can you use a variable instead of hardcoding the address? 

> `  const delegateTransaction3 = await TokenContract.delegate(wallet.address);'

- for these, can we reduce the code with a loop, and organize the numbering to be linear

**Comment by myweb3journey** [comment]
Thanks for the through review, great points will work towards: 
- slimming down for current env
- using a var instead of hardcoding the address
- will work on reducing the code w/ a loop + organizing to be more linear!
